#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Reflection;using UnityEditor;using UnityEngine;using UnityEngine.UIElements;using CityForgeV3.UI;using CityForgeV3.World;
[InitializeOnLoad] public static class BuildingInspectorReview {
 const string D="/Users/joelinstrum/dev/CityForgeMCP/artifacts/fixes/lot-building-inspector-v01/";
 static BuildingInspectorReview(){EditorApplication.update+=Poll;}
 static readonly BindingFlags F=BindingFlags.NonPublic|BindingFlags.Instance;
 static CityForgeApp App()=>UnityEngine.Object.FindFirstObjectByType<CityForgeApp>();
 static LotWorldController World()=>UnityEngine.Object.FindFirstObjectByType<LotWorldController>();
 static void Poll(){var p="/tmp/cityforge-building-inspector-command.txt";if(EditorApplication.isCompiling||EditorApplication.isUpdating||!File.Exists(p))return;var c=File.ReadAllText(p).Trim();File.Delete(p);try{
 if(c=="load"){App().OpenLumberMillQa();if(!World().LoadLot("lumber-mill"))throw new Exception("Saved lot missing");}
 else if(c.StartsWith("category-")){typeof(CityForgeApp).GetMethod("RemoveDocumentModal",F).Invoke(App(),null);var field=typeof(CityForgeApp).GetField("_lotEditorCategory",F);typeof(CityForgeApp).GetMethod("SetLotEditorCategory",F).Invoke(App(),new[]{Enum.Parse(field.FieldType,c.Substring(9))});}
 else if(c.StartsWith("transport-click-")){var root=App().GetComponent<UIDocument>().rootVisualElement;var b=root.Q<Button>("transport-choice-"+c.Substring(16));using(var e=NavigationSubmitEvent.GetPooled()){e.target=b;b.SendEvent(e);}}
 else if(c=="transport-audit"){var root=App().GetComponent<UIDocument>().rootVisualElement;var buttons=root.Query<Button>().ToList();var road=buttons.First(x=>x.name=="Roads");var transport=buttons.First(x=>x.name=="Transport");if(road.resolvedStyle.backgroundImage.texture?.name!="CityForge Road Tool Icon")throw new Exception("Missing road icon");if(transport.resolvedStyle.backgroundImage.texture?.name!="roads-car-v74")throw new Exception("Missing car icon");if(buttons.Any(x=>x.name=="Railroad"))throw new Exception("Railroad still on toolbar");var category=App().ActiveLotEditorCategory.ToString();if(category=="Transport"&&root.Query<Button>().ToList().Count(x=>x.name.StartsWith("transport-choice-"))!=3)throw new Exception("Missing flyout categories");File.AppendAllText("/Users/joelinstrum/dev/CityForgeMCP/artifacts/fixes/transport-toolbar-v01/audit.txt","PASS category="+category+"; road icon; transport car; no standalone railroad; labels="+string.Join("|",root.Query<Label>().ToList().Where(x=>x.ClassListContains("inspector-title")).Select(x=>x.text))+"\n");}
 else if(c=="new-dialog"){typeof(CityForgeApp).GetMethod("ComposeNewLotDialog",F).Invoke(App(),null);}
 else if(c=="general"){typeof(CityForgeApp).GetMethod("RemoveDocumentModal",F).Invoke(App(),null);var field=typeof(CityForgeApp).GetField("_lotEditorCategory",F);field.SetValue(App(),Enum.Parse(field.FieldType,"Main"));typeof(CityForgeApp).GetField("_lotEditorCategoryExpanded",F).SetValue(App(),true);typeof(CityForgeApp).GetMethod("RefreshLotEditor",F).Invoke(App(),null);}
 else if(c.StartsWith("choice-open-")){var root=App().GetComponent<UIDocument>().rootVisualElement;var b=root.Query<Button>(className:"cf-choice-display").ToList()[int.Parse(c.Substring(12))];using(var e=NavigationSubmitEvent.GetPooled()){e.target=b;b.SendEvent(e);}}
 else if(c=="choice-audit"){var root=App().GetComponent<UIDocument>().rootVisualElement;var overlay=root.Q("cf-choice-overlay");var menu=root.Q("cf-choice-menu");if(overlay==null||menu==null||root[root.childCount-1]!=overlay)throw new Exception("Dropdown is not above other UI");var opts=menu.Query<Button>(className:"cf-choice-option").ToList();if(opts.Count==0||menu.resolvedStyle.backgroundColor.a<.99f||menu.worldBound.yMin<0||menu.worldBound.yMax>root.worldBound.yMax+1)throw new Exception("Dropdown bounds or opacity incorrect");File.AppendAllText("/Users/joelinstrum/dev/CityForgeMCP/artifacts/fixes/lot-dropdown-layering-v01/audit.txt","PASS root foreground; opaque; in bounds; choices="+string.Join(",",opts.Select(x=>x.text))+"\n");}
 else if(c=="choice-select"){var root=App().GetComponent<UIDocument>().rootVisualElement;var b=root.Q("cf-choice-menu").Query<Button>().ToList().Last();using(var e=NavigationSubmitEvent.GetPooled()){e.target=b;b.SendEvent(e);}if(root.Q("cf-choice-overlay")!=null)throw new Exception("Selection did not close popup");}
 else if(c=="choice-escape"){var root=App().GetComponent<UIDocument>().rootVisualElement;var b=root.Q("cf-choice-menu").Query<Button>().ToList().First();using(var e=KeyDownEvent.GetPooled(new Event{type=EventType.KeyDown,keyCode=KeyCode.Escape})){e.target=b;b.SendEvent(e);}if(root.Q("cf-choice-overlay")!=null)throw new Exception("Escape did not close popup");}
 else if(c=="choice-outside"){var root=App().GetComponent<UIDocument>().rootVisualElement;var o=root.Q("cf-choice-overlay");using(var e=PointerDownEvent.GetPooled(new Event{type=EventType.MouseDown,button=0,mousePosition=Vector2.one})){e.target=o;o.SendEvent(e);}if(root.Q("cf-choice-overlay")!=null)throw new Exception("Outside click did not dismiss");}
 else if(c=="gesture"){var root=App().GetComponent<UIDocument>().rootVisualElement;var viewport=root.Q<VisualElement>("road-grid-viewport-input");var camera=(Camera)typeof(LotWorldController).GetField("_camera",F).GetValue(World());var pkg=World().GetComponentsInChildren<CityForgeV3.Buildings3D.Building3DPackageInstance>().First(x=>x.name=="3D Building — Linstrum Lumber Mill");var bounds=pkg.GetComponentsInChildren<Renderer>().First().bounds;foreach(var r in pkg.GetComponentsInChildren<Renderer>())bounds.Encapsulate(r.bounds);var v=camera.WorldToViewportPoint(bounds.center);var point=new Vector2(v.x*viewport.resolvedStyle.width,(1-v.y)*viewport.resolvedStyle.height);using(var e=PointerDownEvent.GetPooled(new Event{type=EventType.MouseDown,button=0,mousePosition=point})){e.target=viewport;viewport.SendEvent(e);}root.schedule.Execute(()=>{if(viewport.panel==null){File.WriteAllText(D+"gesture.txt","FAIL viewport detached during mouse hold");return;}using(var e=PointerUpEvent.GetPooled(new Event{type=EventType.MouseUp,button=0,mousePosition=point})){e.target=viewport;viewport.SendEvent(e);}File.WriteAllText(D+"gesture.txt","selected="+World().SelectedBuilding3DIndex+" point="+point);}).StartingIn(200);}
 else if(c.StartsWith("button-")){var key=c.Substring(7);var root=App().GetComponent<UIDocument>().rootVisualElement;var button=key=="simulate"?root.Query<Button>().ToList().First(x=>x.text=="SIMULATE BUILD"):root.Q<Button>("selected-building-rotate-"+key);using(var e=NavigationSubmitEvent.GetPooled()){e.target=button;button.SendEvent(e);}}
 else if(c=="trace"){var root=App().GetComponent<UIDocument>().rootVisualElement;root.RegisterCallback<PointerDownEvent>(e=>File.AppendAllText(D+"events.txt","DOWN "+e.position+" target="+(e.target as VisualElement)?.name+" selected="+World().SelectedBuilding3DIndex+"\n"),TrickleDown.TrickleDown);root.RegisterCallback<PointerUpEvent>(e=>File.AppendAllText(D+"events.txt","UP "+e.position+" target="+(e.target as VisualElement)?.name+" selected="+World().SelectedBuilding3DIndex+"\n"),TrickleDown.TrickleDown);}
 else if(c=="closed"){World().DeselectBuilding3D();typeof(CityForgeApp).GetField("_lotInspectorVisible",F).SetValue(App(),false);typeof(CityForgeApp).GetField("_lotEditorCategoryExpanded",F).SetValue(App(),false);typeof(CityForgeApp).GetMethod("RefreshLotEditor",F).Invoke(App(),null);}
 else if(c=="audit"){var root=App().GetComponent<UIDocument>().rootVisualElement;var inspector=root.Q<VisualElement>("selected-building-inspector");if(inspector==null)throw new Exception("Selected Building panel not visible");if(root.Q<Label>("selected-building-name")?.text!=World().SelectedBuilding3DDisplayName)throw new Exception("Wrong building name");if(root.Q<Button>("selected-building-rotate-left")==null||root.Q<Button>("selected-building-rotate-right")==null)throw new Exception("Missing rotations");if(root.Q<VisualElement>("building-3d-library-modal")!=null||root.Q<VisualElement>("buildings-category-panel")!=null)throw new Exception("Picker opened");var buttons=inspector.Query<Button>().ToList();if(!buttons.Any(b=>b.text=="SIMULATE BUILD"))throw new Exception("Simulate build missing");File.WriteAllText(D+"audit.txt","PASS visible named building inspector; rotate left/right; Simulate build; no building library modal; name="+World().SelectedBuilding3DDisplayName);}
 else if(c=="state"){var root=App().GetComponent<UIDocument>().rootVisualElement;File.WriteAllText(D+"state.txt","selected="+World().SelectedBuilding3DIndex+" name="+World().SelectedBuilding3DDisplayName+" category="+App().ActiveLotEditorCategory+" picker="+App().IsLotEditorCategoryExpanded+" construction="+(World().SelectedBuildingConstruction?.StageLabel??"none")+"\n"+string.Join("\n",World().GetComponentsInChildren<CityForgeV3.Buildings3D.Building3DPackageInstance>().Select(x=>x.name+" yaw="+x.transform.eulerAngles.y)));}
 else if(c.StartsWith("capture-")){var gv=EditorWindow.GetWindow(typeof(UnityEditor.Editor).Assembly.GetType("UnityEditor.GameView"));if(gv.maximized)gv.maximized=false;ScreenCapture.CaptureScreenshot(D+c+".png");gv.Repaint();}
 File.WriteAllText("/tmp/cityforge-building-inspector-result.txt","OK "+c);
 }catch(Exception e){Debug.LogException(e);File.WriteAllText("/tmp/cityforge-building-inspector-result.txt",e.ToString());}}
}
#endif
