#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEditor.Animations;using UnityEngine;
[InitializeOnLoad] public static class DockWorkerImport
{
 const string Root="Assets/CityForgeV3/Resources/CityForgeV3/Characters/DockWorkerV01";
 static DockWorkerImport(){EditorApplication.update+=Poll;}
 static void Poll(){var p="/tmp/cityforge-dock-import.txt";if(EditorApplication.isCompiling||EditorApplication.isUpdating||!File.Exists(p))return;File.Delete(p);try{Build();File.WriteAllText("/tmp/cityforge-dock-import-result.txt","OK");}catch(Exception e){File.WriteAllText("/tmp/cityforge-dock-import-result.txt",e.ToString());Debug.LogException(e);}}
 static Texture2D Tex(string name,bool srgb,bool normal=false){var p=Root+"/Textures/"+name;var i=(TextureImporter)AssetImporter.GetAtPath(p);i.sRGBTexture=srgb;i.textureType=normal?TextureImporterType.NormalMap:TextureImporterType.Default;i.isReadable=!normal;i.maxTextureSize=2048;i.textureCompression=TextureImporterCompression.CompressedHQ;i.SaveAndReimport();return AssetDatabase.LoadAssetAtPath<Texture2D>(p);}
 static void Build(){AssetDatabase.Refresh();var p=Root+"/DockWorker_Source.fbx";var i=(ModelImporter)AssetImporter.GetAtPath(p);i.animationType=ModelImporterAnimationType.Generic;i.avatarSetup=ModelImporterAvatarSetup.CreateFromThisModel;i.importAnimation=true;i.optimizeGameObjects=false;i.materialImportMode=ModelImporterMaterialImportMode.None;i.animationCompression=ModelImporterAnimationCompression.Off;i.SaveAndReimport();var clips=i.defaultClipAnimations;foreach(var c in clips){c.name=c.takeName.ToLowerInvariant().Contains("walk")?"Walk":"Idle";c.loopTime=true;c.loopPose=false;c.lockRootPositionXZ=true;c.lockRootHeightY=true;c.lockRootRotation=true;}i.clipAnimations=clips;i.SaveAndReimport();var all=AssetDatabase.LoadAllAssetsAtPath(p).OfType<AnimationClip>().Where(c=>!c.name.StartsWith("__preview__")).ToArray();var idle=all.First(c=>c.name=="Idle");var walk=all.First(c=>c.name=="Walk");
 var albedo=Tex("Albedo.jpg",true);var normal=Tex("Normal.jpg",false,true);var rough=Tex("Roughness.jpg",false);var metal=Tex("Metallic.jpg",false);var packed=new Texture2D(rough.width,rough.height,TextureFormat.RGBA32,false,true);var pixels=new Color[rough.width*rough.height];for(int y=0;y<rough.height;y++)for(int x=0;x<rough.width;x++){float u=(x+.5f)/rough.width,v=(y+.5f)/rough.height;pixels[y*rough.width+x]=new Color(metal.GetPixelBilinear(u,v).r,0,0,1-rough.GetPixel(x,y).r);}packed.SetPixels(pixels);packed.Apply();File.WriteAllBytes(Root+"/Textures/MetallicSmoothness.png",packed.EncodeToPNG());UnityEngine.Object.DestroyImmediate(packed);AssetDatabase.Refresh();var gloss=Tex("MetallicSmoothness.png",false);
 var mat=new Material(Shader.Find("Standard")){name="Dock Worker Original PBR",mainTexture=albedo,color=Color.white};mat.SetTexture("_BumpMap",normal);mat.EnableKeyword("_NORMALMAP");mat.SetTexture("_MetallicGlossMap",gloss);mat.SetFloat("_GlossMapScale",1);mat.EnableKeyword("_METALLICGLOSSMAP");AssetDatabase.CreateAsset(mat,Root+"/DockWorker.mat");
 var ctrl=AnimatorController.CreateAnimatorControllerAtPath(Root+"/DockWorker.controller");ctrl.AddParameter("Walking",AnimatorControllerParameterType.Bool);var sm=ctrl.layers[0].stateMachine;var a=sm.AddState("Idle");a.motion=idle;var b=sm.AddState("Walk");b.motion=walk;sm.defaultState=a;var ab=a.AddTransition(b);ab.hasExitTime=false;ab.duration=.15f;ab.AddCondition(AnimatorConditionMode.If,0,"Walking");var ba=b.AddTransition(a);ba.hasExitTime=false;ba.duration=.15f;ba.AddCondition(AnimatorConditionMode.IfNot,0,"Walking");
 var root=new GameObject("Dock Worker");var model=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(p));model.transform.SetParent(root.transform,false);var renderers=model.GetComponentsInChildren<Renderer>();var bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);model.transform.localScale*=1.8f/bounds.size.y;bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);model.transform.localPosition-=new Vector3(bounds.center.x,bounds.min.y,bounds.center.z);foreach(var r in renderers)r.sharedMaterial=mat;var animator=model.GetComponent<Animator>();animator.runtimeAnimatorController=ctrl;animator.applyRootMotion=false;animator.cullingMode=AnimatorCullingMode.AlwaysAnimate;PrefabUtility.SaveAsPrefabAsset(root,Root+"/DockWorkerV01.prefab");File.WriteAllText("/Users/joelinstrum/dev/CityForgeMCP/artifacts/characters/dock-worker/v01/unity-import.txt","height=1.8m; Generic rig; Idle="+idle.length+"s; Walk="+walk.length+"s; triangles="+model.GetComponentsInChildren<SkinnedMeshRenderer>().Sum(x=>x.sharedMesh.triangles.Length/3));UnityEngine.Object.DestroyImmediate(root);AssetDatabase.SaveAssets();}
}
#endif
