#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEditor;using UnityEngine;using CityForgeV3.Buildings3D;using CityForgeV3.World;using CityForgeV3.UI;
 public static class LumberMillMainReview {
 const string B="Assets/CityForgeV3/Resources/CityForgeV3/Buildings3D/LumberMillV01";
 const string D="/Users/joelinstrum/dev/CityForgeMCP/artifacts/buildings/lumber-mill/v01/main-review/";
 [Serializable] class Contract{public float[] unityWheelPivot;public float defaultRPM;public Foundation foundation;}
 [Serializable] class Foundation{public float[] boundsMin,boundsMax;}
 static LumberMillMainReview(){EditorApplication.update+=Poll;}
 static LotWorldController World()=>UnityEngine.Object.FindFirstObjectByType<LotWorldController>();
 static Building3DPackageInstance Target()=>UnityEngine.Object.FindObjectsByType<Building3DPackageInstance>(FindObjectsSortMode.None).First(x=>x.Package!=null&&x.Package.AssetId=="lumber-mill-v01"&&!x.name.ToLowerInvariant().Contains("shadow"));
 static void Poll(){var p="/tmp/cityforge-main-mill-command.txt";if(EditorApplication.isCompiling||EditorApplication.isUpdating||!File.Exists(p))return;var c=File.ReadAllText(p).Trim();File.Delete(p);try{
 if(c=="scale-compare"){UnityEngine.Object.FindFirstObjectByType<CityForgeApp>().OpenLumberMillQa();World().PlacePropForQa(LotWorldController.HooliganCharacterId,8,-4);Focus();}else if(c=="build")Build();else if(c=="scene"){UnityEngine.Object.FindFirstObjectByType<CityForgeApp>().OpenLumberMillQa();World().DeselectBuilding3D();Focus();}
 else if(c=="dump"){File.WriteAllLines(D+"runtime-dump.txt",Target().GetComponentsInChildren<Transform>().Select(x=>x.name+" pos="+x.position+" rot="+x.eulerAngles+" scale="+x.lossyScale));File.AppendAllText(D+"runtime-dump.txt","\nCAMERAS\n"+string.Join("\n",UnityEngine.Object.FindObjectsByType<Camera>(FindObjectsSortMode.None).Select(x=>x.name+" pos="+x.transform.position+" rot="+x.transform.eulerAngles+" near="+x.nearClipPlane+" far="+x.farClipPlane)));}else if(c=="focus")Focus();else if(c=="test")Test();else if(c=="rotate"){World().SelectBuilding3DForQa(0);World().RotateSelectedBuilding3D(1);World().DeselectBuilding3D();Focus();}
 else if(c=="stop-wheel")Target().GetComponentInChildren<BuildingWheelRotation>().SetRunning(false);else if(c=="run-wheel")Target().GetComponentInChildren<BuildingWheelRotation>().SetRunning(true);
 else if(c.StartsWith("capture-")){Application.runInBackground=true;var gv=EditorWindow.GetWindow(typeof(UnityEditor.Editor).Assembly.GetType("UnityEditor.GameView"));if(gv.maximized)throw new Exception("Expected docked Game view");ScreenCapture.CaptureScreenshot(D+c+".png");gv.Repaint();File.WriteAllText(D+c+".txt","Actual Game view; project="+Application.dataPath+"; docked="+!gv.maximized+"; wheel angle="+Target().GetComponentInChildren<BuildingWheelRotation>().Angle);}
 File.WriteAllText("/tmp/cityforge-main-mill-result.txt","OK "+c);
 }catch(Exception e){Debug.LogException(e);File.WriteAllText("/tmp/cityforge-main-mill-result.txt",e.ToString());}}
 static void Focus(){var t=Target();var rs=t.GetComponentsInChildren<Renderer>();var b=rs[0].bounds;foreach(var r in rs)b.Encapsulate(r.bounds);var p=b.center;var shift=b.center.y/Mathf.Tan(20*Mathf.Deg2Rad)/Mathf.Sqrt(2);World().SetQaCameraPan(0,0);World().SetQaOrthographicSize(9);var camera=World().GetComponentInChildren<Camera>();if(camera!=null)camera.transform.position=b.center-camera.transform.forward*80;Application.runInBackground=true;}
 static T Save<T>(T value,string path)where T:UnityEngine.Object{var prior=AssetDatabase.LoadAssetAtPath<T>(path);if(prior==null){AssetDatabase.CreateAsset(value,path);return value;}EditorUtility.CopySerialized(value,prior);UnityEngine.Object.DestroyImmediate(value);return prior;}
 [MenuItem("City Forge/3D Buildings/Build Lumber Mill")]
 public static void Build(){if(Application.isPlaying)throw new Exception("Stop review before build");foreach(var d in new[]{"Meshes","Materials","Prefabs"})Directory.CreateDirectory(B+"/"+d);AssetDatabase.Refresh();var imp=(ModelImporter)AssetImporter.GetAtPath(B+"/Source/LumberMill_v01.fbx");imp.materialImportMode=ModelImporterMaterialImportMode.None;imp.importAnimation=false;imp.isReadable=true;imp.SaveAndReimport();
 foreach(var f in new[]{"Albedo.jpg","Normal.jpg"}){var ti=(TextureImporter)AssetImporter.GetAtPath(B+"/Textures/"+f);ti.maxTextureSize=2048;ti.textureCompression=TextureImporterCompression.Uncompressed;ti.anisoLevel=8;if(f=="Normal.jpg")ti.textureType=TextureImporterType.NormalMap;else ti.sRGBTexture=true;ti.SaveAndReimport();}
 var mat=new Material(Shader.Find("Standard"));mat.name="Mill_WeatheredWoodAndStone";mat.mainTexture=AssetDatabase.LoadAssetAtPath<Texture2D>(B+"/Textures/Albedo.jpg");mat.SetTexture("_BumpMap",AssetDatabase.LoadAssetAtPath<Texture2D>(B+"/Textures/Normal.jpg"));mat.EnableKeyword("_NORMALMAP");mat.SetFloat("_BumpScale",1);mat.SetFloat("_Metallic",0);mat.SetFloat("_Glossiness",.1f);mat.SetFloat("_SpecularHighlights",0);mat.SetFloat("_GlossyReflections",0);mat.EnableKeyword("_SPECULARHIGHLIGHTS_OFF");mat.EnableKeyword("_GLOSSYREFLECTIONS_OFF");mat=Save(mat,B+"/Materials/Mill.mat");
 var cfg=JsonUtility.FromJson<Contract>(File.ReadAllText(D+"material-and-wheel-contract.json"));var pivot=new Vector3(cfg.unityWheelPivot[0],cfg.unityWheelPivot[1],cfg.unityWheelPivot[2]);var visual=UnityEngine.Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(B+"/Source/LumberMill_v01.fbx"));visual.name="LumberMillVisual";
 try{var renderers=visual.GetComponentsInChildren<MeshRenderer>();Transform wheel=null;
 foreach(var r in renderers){var mf=r.GetComponent<MeshFilter>();var m=UnityEngine.Object.Instantiate(mf.sharedMesh);var matrix=visual.transform.worldToLocalMatrix*r.transform.localToWorldMatrix;var normalMatrix=matrix.inverse.transpose;bool moving=r.name=="Mill_Wheel";File.AppendAllText(D+"mesh-determinants.txt",r.name+" det="+matrix.determinant+" transform="+matrix+"\n");if(matrix.determinant<0){for(int si=0;si<m.subMeshCount;si++){var ix=m.GetTriangles(si);for(int i=0;i<ix.Length;i+=3){var a=ix[i];ix[i]=ix[i+2];ix[i+2]=a;}m.SetTriangles(ix,si);}}m.vertices=m.vertices.Select(v=>matrix.MultiplyPoint3x4(v)-(moving?pivot:Vector3.zero)).ToArray();m.normals=m.normals.Select(n=>normalMatrix.MultiplyVector(n).normalized).ToArray();m.tangents=m.tangents.Select(t=>{var v=matrix.MultiplyVector(new Vector3(t.x,t.y,t.z)).normalized;return new Vector4(v.x,v.y,v.z,t.w*(matrix.determinant<0?-1:1));}).ToArray();m.RecalculateBounds();mf.sharedMesh=Save(m,B+"/Meshes/"+r.name+".asset");r.sharedMaterial=mat;r.transform.SetParent(visual.transform,false);r.transform.localPosition=moving?pivot:Vector3.zero;r.transform.localRotation=Quaternion.identity;r.transform.localScale=Vector3.one;if(moving)wheel=r.transform;}
 if(wheel==null)throw new Exception("Wheel missing");visual.AddComponent<BuildingWheelRotation>().Configure(wheel,Vector3.forward,4);var vp=PrefabUtility.SaveAsPrefabAsset(visual,B+"/Prefabs/LumberMillVisual.prefab");var pkg=ScriptableObject.CreateInstance<Building3DPackage>();pkg.AssetId="lumber-mill-v01";pkg.SourceProvenance="Joel-supplied lumber mill; separate repaired wheel, original atlas, metric registration v01";pkg.AuthoredScale=Vector3.one;pkg.FrontYawDegrees=90;pkg.UseCrossFade=false;pkg.FootprintMeters=new Vector2(cfg.foundation.boundsMax[0]-cfg.foundation.boundsMin[0],cfg.foundation.boundsMax[1]-cfg.foundation.boundsMin[1]);pkg.Representations=new List<Building3DRepresentation>{new Building3DRepresentation{Level=Building3DLevel.LOD0,ScreenRelativeHeight=.001f,VisualPrefab=vp,LocalScale=Vector3.one,TargetTriangleBudget=50000}};pkg=Save(pkg,B+"/LumberMillV01.asset");var root=new GameObject("Lumber Mill");root.AddComponent<Building3DPackageInstance>().Configure(pkg);PrefabUtility.SaveAsPrefabAsset(root,B+"/Prefabs/LumberMillV01.prefab");UnityEngine.Object.DestroyImmediate(root);AssetDatabase.SaveAssets();BuildingContentCatalog.InvalidateCache();File.WriteAllText(D+"unity-build.txt","PASS renderers="+renderers.Length+"; triangles="+renderers.Sum(r=>r.GetComponent<MeshFilter>().sharedMesh.triangles.Length/3)+"; pivot="+pivot+"; footprint="+pkg.FootprintMeters);
 }finally{UnityEngine.Object.DestroyImmediate(visual);}}
 static void Test(){var t=Target();var w=t.GetComponentInChildren<BuildingWheelRotation>();var body=t.GetComponentsInChildren<MeshFilter>().First(x=>x.name=="Mill_Building");var initial=body.transform.localToWorldMatrix;var center=w.Wheel.position;var radius=Vector3.Distance(w.Wheel.TransformPoint(w.Wheel.GetComponent<MeshFilter>().sharedMesh.vertices[0]),center);w.SetRunning(false);float a=w.Angle;if(Mathf.Abs(w.Evaluate(Time.timeAsDouble+10)-a)>.01)throw new Exception("Stop failed");w.SetRPM(4);w.SetRunning(true);if(Mathf.Abs(Mathf.DeltaAngle(w.Evaluate(Time.timeAsDouble),w.Evaluate(Time.timeAsDouble+15)))>.01)throw new Exception("Full turn failed");w.SetRPM(-4);if(Mathf.Abs(Mathf.DeltaAngle(w.Evaluate(Time.timeAsDouble),w.Evaluate(Time.timeAsDouble+1))+24)>.01)throw new Exception("Reverse failed");w.SetRPM(4);if(body.transform.localToWorldMatrix!=initial||Vector3.Distance(w.Wheel.position,center)>.0001)throw new Exception("Building or axle moved");var wheels=World().GetComponentsInChildren<BuildingWheelRotation>();foreach(var s in wheels)if(Mathf.Abs(Mathf.DeltaAngle(s.Angle,w.Angle))>.01)throw new Exception("Shadow phase mismatch");File.WriteAllText(D+"motion-validation.txt","PASS stopped angle; 15-second full rotation at 4RPM; reverse; static body and fixed axle; synchronized wheel/shadow controls="+wheels.Length+"; initial sample radius="+radius);}
}
#endif
