#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using UnityEditor;using UnityEngine;using CityForgeV3.World;using CityForgeV3.UI;using UnityEngine.UIElements;using System.Reflection;
 public static class WoodenBargeImport {
 const string Root="Assets/CityForgeV3/Resources/CityForgeV3/Vehicles/WoodenBargeV01";
 const string Report="/Users/joelinstrum/dev/CityForgeMCP/artifacts/vehicles/wooden-barge/v01/";
 static WoodenBargeImport(){EditorApplication.update+=Poll;}
 static void Poll(){var path="/tmp/cityforge-barge-command.txt";if(EditorApplication.isCompiling||EditorApplication.isUpdating||!File.Exists(path))return;var cmd=File.ReadAllText(path).Trim();File.Delete(path);try{if(cmd=="build")Build();if(cmd=="thumbnail")Thumbnail();if(cmd=="library-test")LibraryTest();if(cmd=="review")Review();if(cmd=="validate")Validate();if(cmd=="place-ui")PlaceUi();if(cmd=="save-test")SaveTest();if(cmd=="focus")Focus();if(cmd=="load-review"){var w=UnityEngine.Object.FindFirstObjectByType<LotWorldController>();w.LoadLot("wooden-barge-review-v01");Focus();}File.WriteAllText("/tmp/cityforge-barge-result.txt","OK "+cmd);}catch(Exception e){File.WriteAllText("/tmp/cityforge-barge-result.txt",e.ToString());Debug.LogException(e);}}
 static Texture2D Texture(string name,bool srgb,bool normal=false){var path=Root+"/Textures/"+name;var i=(TextureImporter)AssetImporter.GetAtPath(path);i.sRGBTexture=srgb;i.textureType=normal?TextureImporterType.NormalMap:TextureImporterType.Default;i.maxTextureSize=2048;i.isReadable=!normal;i.textureCompression=TextureImporterCompression.Uncompressed;i.SaveAndReimport();return AssetDatabase.LoadAssetAtPath<Texture2D>(path);}
 static Bounds BoundsOf(GameObject go){var rs=go.GetComponentsInChildren<Renderer>();var b=rs[0].bounds;foreach(var r in rs)b.Encapsulate(r.bounds);return b;}
 static void Build(){AssetDatabase.Refresh();var importer=(ModelImporter)AssetImporter.GetAtPath(Root+"/WoodenBarge_Source.fbx");importer.materialImportMode=ModelImporterMaterialImportMode.None;importer.isReadable=true;importer.SaveAndReimport();
 var albedo=Texture("Albedo.jpg",true);var normal=Texture("Normal.jpg",false,true);var rough=Texture("Roughness.jpg",false);var metal=Texture("Metallic.jpg",false);
 var packed=new Texture2D(rough.width,rough.height,TextureFormat.RGBA32,false,true);var pixels=new Color[rough.width*rough.height];for(int y=0;y<rough.height;y++)for(int x=0;x<rough.width;x++){float u=(x+.5f)/rough.width,v=(y+.5f)/rough.height;pixels[y*rough.width+x]=new Color(metal.GetPixelBilinear(u,v).r,0,0,1-rough.GetPixel(x,y).r);}packed.SetPixels(pixels);packed.Apply();File.WriteAllBytes(Root+"/Textures/MetallicSmoothness.png",packed.EncodeToPNG());UnityEngine.Object.DestroyImmediate(packed);AssetDatabase.Refresh();var gloss=Texture("MetallicSmoothness.png",false);
 var mat=new Material(Shader.Find("Standard")){name="Wooden Barge — Original PBR",color=Color.white,mainTexture=albedo};mat.SetTexture("_BumpMap",normal);mat.EnableKeyword("_NORMALMAP");mat.SetTexture("_MetallicGlossMap",gloss);mat.SetFloat("_GlossMapScale",1);mat.EnableKeyword("_METALLICGLOSSMAP");AssetDatabase.CreateAsset(mat,Root+"/WoodenBarge.mat");
 var root=new GameObject("Wooden Lumber Barge");var model=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(Root+"/WoodenBarge_Source.fbx"));model.transform.SetParent(root.transform,false);var b=BoundsOf(model);if(b.size.x>b.size.z)model.transform.localRotation=Quaternion.Euler(0,90,0);b=BoundsOf(model);model.transform.localScale*=10f/b.size.z;b=BoundsOf(model);model.transform.localPosition-=new Vector3(b.center.x,b.min.y,b.center.z);foreach(var renderer in model.GetComponentsInChildren<Renderer>())renderer.sharedMaterial=mat;
 b=BoundsOf(root);PrefabUtility.SaveAsPrefabAsset(root,Root+"/WoodenBargeV01.prefab");File.WriteAllText(Report+"unity-import.txt","Bounds="+b+"; shader=Standard; original albedo/normal; smoothness=1-roughness; length=10m; triangles="+model.GetComponentsInChildren<MeshFilter>().Sum(x=>x.sharedMesh.triangles.Length/3));UnityEngine.Object.DestroyImmediate(root);AssetDatabase.SaveAssets();}
 static void Review(){var w=UnityEngine.Object.FindFirstObjectByType<LotWorldController>();w.NewEmptyLot("Wooden Barge Review",LotType.Mixed,2,2);w.DeselectBuilding3D();var camera=(Camera)typeof(LotWorldController).GetField("_camera",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(w);camera.transform.position=Vector3.zero-camera.transform.forward*40;camera.orthographicSize=7;}
 static void PlaceUi(){var app=UnityEngine.Object.FindFirstObjectByType<CityForgeApp>();var w=UnityEngine.Object.FindFirstObjectByType<LotWorldController>();var root=app.GetComponent<UIDocument>().rootVisualElement;var button=root.Q<Button>("place-wooden-barge");using(var e=NavigationSubmitEvent.GetPooled()){e.target=button;button.SendEvent(e);}root.schedule.Execute(()=>{var viewport=root.Q("road-grid-viewport-input");var camera=(Camera)typeof(LotWorldController).GetField("_camera",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(w);var v=camera.WorldToViewportPoint(Vector3.zero);var point=new Vector2(v.x*viewport.resolvedStyle.width,(1-v.y)*viewport.resolvedStyle.height);using(var e=PointerDownEvent.GetPooled(new Event{type=EventType.MouseDown,button=0,mousePosition=point})){e.target=viewport;viewport.SendEvent(e);}using(var e=PointerUpEvent.GetPooled(new Event{type=EventType.MouseUp,button=0,mousePosition=point})){e.target=viewport;viewport.SendEvent(e);}File.WriteAllText(Report+"placement-ui.txt","count="+w.PropCount+" selectedBoat="+w.SelectedPropIsBoat);}).StartingIn(250);}
 static void SaveTest(){var w=UnityEngine.Object.FindFirstObjectByType<LotWorldController>();if(!w.SelectedPropIsBoat||w.PropCount!=1)throw new Exception("UI placement failed");if(!w.RotateSelectedProp(1))throw new Exception("Boat rotation failed");var path=w.SaveLotAs("Wooden Barge Review v01");var id=Path.GetFileNameWithoutExtension(path);if(!w.LoadLot(id))throw new Exception("Reload failed "+path);var barge=w.GetComponentsInChildren<Transform>().Where(x=>x.name=="Prop — "+LotWorldController.WoodenBargePropId).Last();if(w.PropCount!=1||Mathf.Abs(Mathf.DeltaAngle(barge.eulerAngles.y,90))>.01f)throw new Exception("Boat save did not retain rotation");File.WriteAllText(Report+"save-roundtrip.txt","PASS UI placement, 90 degree rotation, saved and reloaded one barge; "+path);}
 static void Focus(){var w=UnityEngine.Object.FindFirstObjectByType<LotWorldController>();var camera=(Camera)typeof(LotWorldController).GetField("_camera",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(w);var barge=w.GetComponentsInChildren<Transform>().Where(x=>x.name=="Prop — "+LotWorldController.WoodenBargePropId).Last();var b=BoundsOf(barge.gameObject);camera.transform.position=b.center-camera.transform.forward*40;camera.orthographicSize=6;w.SetPropPlacementPreview("");}
 static void Thumbnail(){var preview=new PreviewRenderUtility();try{var go=UnityEngine.Object.Instantiate(Resources.Load<GameObject>(LotWorldController.WoodenBargeResourcePath));preview.AddSingleGO(go);var b=BoundsOf(go);preview.camera.orthographic=true;preview.camera.orthographicSize=4.4f;preview.camera.nearClipPlane=.1f;preview.camera.farClipPlane=100;preview.camera.transform.position=b.center+new Vector3(12,10,-16);preview.camera.transform.LookAt(b.center);preview.camera.clearFlags=CameraClearFlags.SolidColor;preview.camera.backgroundColor=new Color(.065f,.105f,.13f,1);preview.ambientColor=new Color(.45f,.45f,.45f,1);preview.lights[0].intensity=1.1f;preview.lights[0].transform.rotation=Quaternion.Euler(45,25,0);preview.lights[1].intensity=.5f;preview.BeginStaticPreview(new Rect(0,0,512,320));preview.Render();var texture=preview.EndStaticPreview();var path="Assets/CityForgeV3/Resources/CityForgeV3/Boats/Thumbnails/wooden-lumber-barge-v01.png";Directory.CreateDirectory(Path.GetDirectoryName(path));File.WriteAllBytes(path,texture.EncodeToPNG());UnityEngine.Object.DestroyImmediate(texture);AssetDatabase.Refresh();var importer=(TextureImporter)AssetImporter.GetAtPath(path);importer.mipmapEnabled=false;importer.textureCompression=TextureImporterCompression.Uncompressed;importer.SaveAndReimport();}finally{preview.Cleanup();}}
 static void LibraryTest(){var app=UnityEngine.Object.FindFirstObjectByType<CityForgeApp>();var w=UnityEngine.Object.FindFirstObjectByType<LotWorldController>();var root=app.GetComponent<UIDocument>().rootVisualElement;if(root.Q("boat-library-panel")==null)throw new Exception("Boats did not open library");var search=root.Q<TextField>("boat-library-search");search.value="not-a-boat";if(root.Q<Button>("boat-select-"+LotWorldController.WoodenBargePropId)!=null)throw new Exception("Search did not filter");search.value="barge";var card=root.Q<Button>("boat-select-"+LotWorldController.WoodenBargePropId);if(card==null||card.Q<Image>()?.image==null)throw new Exception("Missing boat thumbnail");var count=w.PropCount;using(var e=NavigationSubmitEvent.GetPooled()){e.target=card;card.SendEvent(e);}if(root.Q("document-modal")!=null||w.PropCount!=count)throw new Exception("Selection should close modal without placing yet");var id=(string)typeof(CityForgeApp).GetField("_placementPropId",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(app);if(id!=LotWorldController.WoodenBargePropId)throw new Exception("Wrong boat armed");root.schedule.Execute(()=>{var viewport=root.Q("road-grid-viewport-input");var camera=(Camera)typeof(LotWorldController).GetField("_camera",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(w);var v=camera.WorldToViewportPoint(Vector3.zero);var point=new Vector2(v.x*viewport.resolvedStyle.width,(1-v.y)*viewport.resolvedStyle.height);using(var e=PointerDownEvent.GetPooled(new Event{type=EventType.MouseDown,button=0,mousePosition=point})){e.target=viewport;viewport.SendEvent(e);}using(var e=PointerUpEvent.GetPooled(new Event{type=EventType.MouseUp,button=0,mousePosition=point})){e.target=viewport;viewport.SendEvent(e);}if(w.PropCount!=count+1||!w.SelectedPropIsBoat)throw new Exception("Next click did not place one boat");File.WriteAllText("/Users/joelinstrum/dev/CityForgeMCP/artifacts/fixes/boat-library-v01/validation.txt","PASS Boats opens thumbnail library; search filters and restores; thumbnail selection closes modal and arms without placing; next viewport click places one selected boat.");}).StartingIn(250);}
 static void Validate(){var prefab=Resources.Load<GameObject>(LotWorldController.WoodenBargeResourcePath);if(prefab==null)throw new Exception("Barge missing");var go=UnityEngine.Object.Instantiate(prefab);var b=BoundsOf(go);if(Mathf.Abs(b.size.z-10)>.01f||Mathf.Abs(b.min.y)>.01f)throw new Exception("Bad scale or grounding");var m=go.GetComponentInChildren<Renderer>().sharedMaterial;if(m.color!=Color.white||m.mainTexture==null||m.GetTexture("_BumpMap")==null||m.GetTexture("_MetallicGlossMap")==null)throw new Exception("Missing source materials");UnityEngine.Object.DestroyImmediate(go);File.WriteAllText(Report+"validation.txt","PASS 10m length; grounded centered prefab; original PBR maps; white tint.");}
}
#endif
